### ISSUE TITLE
Redis scalers are not shown when searched

### ISSUE THREAD

**Issue by thisisobate** [kedacore/keda-docs#854] opened 2022-08-03 04:16 UTC
## Expected Behavior
Show results when a specific scaler is searched.
Bug introduced by #805

## Actual Behavior
Tried using the **Redis** keyword to search through the scaler list and no result was shown.

## Steps to Reproduce the Problem

  1. Navigate to the scaler's page
  2. search "Redis"
  3. Notice that it returns no results even though is present on the scaler's list

## Specifications

  - **KEDA Version:** *Please elaborate*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

**Comment by v-shenoy** [comment] 2022-08-03 06:32
I tried a few queries, and they showed up with no results as well.

![image](https://user-images.githubusercontent.com/38671299/182539539-f966e280-254f-41b9-8cb9-a8ffe8b3383a.png)

![image](https://user-images.githubusercontent.com/38671299/182539583-5e24d7de-a92c-4153-889b-013d5a178d60.png)

![image](https://user-images.githubusercontent.com/38671299/182539653-e3f63b53-6d88-4e76-8966-ab0bce963aea.png)

![image](https://user-images.githubusercontent.com/38671299/182539846-464f6584-28ff-49d6-b1a2-5ea01b1ead3a.png)

**Comment by v-shenoy** [comment] 2022-08-03 06:32
> I tried a few queries, and they showed up with no results as well.
> 


Seems to be some problem with spaces.

**Comment by tomkerkhove** [comment] 2022-08-03 06:33
Duplicate of #857 as this is more than just Redis

**Closed by tomkerkhove** 2022-08-03 06:33 UTC
Labels: bug
