### ISSUE TITLE
Version dropdown for authentication providers uses wrong URL

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#941] opened 2022-09-20 06:45 UTC
The dropdown doesn't work, it points to wrong url (missing `/authentication-providers/`)
![image](https://user-images.githubusercontent.com/4345663/191186184-5d9e092f-77d7-41bb-a49f-39c0d3e02e9f.png)

Kudos to @JorTurFer 

Relates to #711

**Comment by thisisobate** [comment] 2023-03-21 18:58
@tomkerkhove I think this was already fixed in #956. 
Just curious: any reason why you reopened this?

**Comment by JorTurFer** [comment] 2023-03-21 19:16
I think this is solved @tomkerkhove  (I can't reproduce it)
I close the issue, reopen it if you think something is left

**Closed by JorTurFer** 2023-03-21 19:16 UTC
Labels: bug, cant-touch-this
